### PR TITLE
Add support for VS 2019

### PR DESCRIPTION
**Pull request by lewissbaker**

### CODE REVIEW

File: test/io_service_tests.cpp [hunk 1]
```diff
@@ -191,6 +191,10 @@ TEST_CASE("Timer cancellation"
 		}()));
 }
 
+// Disable this test under VS 2019.3
+// Results in ICE compiling the 'startTimer' lambda below.
+#if CPPCORO_COMPILER_MSVC != 192328105
```
Comment (lewissbaker) [inline test/io_service_tests.cpp]: CC: @gornishanov I've just been trying to update cppcoro to work with MSVC 2019.3 and have started encountering some new compiler-crashes. I've disabled the problematic tests for now but wanted to give you a heads up.

**Review by radzevich — COMMENTED** [review]
Hi @lewissbaker . I switched to this branch and got build failed:
```
> ./cake.bat release=debug architecture=x64 lib/build.cake

Traceback (most recent call last):
  File "C:\Projects\Druniks\Druniks.Prototype\lib\cppcoro\tools\cake\src\cake\runner.py", line 454, in run
    configuration = engine.findConfiguration(scriptPath)
  File "C:\Projects\Druniks\Druniks.Prototype\lib\cppcoro\tools\cake\src\cake\engine.py", line 335, in findConfiguration
    return self.getConfiguration(configScript)
  File "C:\Projects\Druniks\Druniks.Prototype\lib\cppcoro\tools\cake\src\cake\engine.py", line 308, in getConfiguration
    script.execute()
  File "C:\Projects\Druniks\Druniks.Prototype\lib\cppcoro\tools\cake\src\cake\script.py", line 273, in execute
    exec byteCode in scriptGlobals
  File "C:\Projects\Druniks\Druniks.Prototype\lib\cppcoro\config.cake", line 70, in <module>
    from cake.library.compilers.msvc import getVisualStudioCompiler, findMsvcInstallDir
ImportError: cannot import name getVisualStudioCompiler
Build failed with 1 errors.
Build took 0:00:00.243.
```
That's because `cake` submodule targeting `clang` branch instead of `master`. Should the submodule branch be also updated in the scope of this PR? 

Thank you!
